## Server
server:
  port: 9000

## MySQL
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/ums?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
